Fix following TypeError exception:
  File NmrDpRemediationMerge.py, line 2042, in mergeLegacyData
    if row[2] != block_id or row[1] not in sf.name:

TypeError: 'in <string>' requires string as left operand, not NoneType